spring.boot.admin.client:
  url: http://localhost:9001
  username: admin
  password: password
  instance:
    metadata:
      user.name: admin
      user.password: password

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
