spring.boot.admin.client:
  url: http://localhost:9001
  username: admin
  password: password
  instance:
    metadata:
      user.name: admin
      user.password: password

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.102:8848
    sentinel:
      transport:
        dashboard: localhost:8048
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/mybatis?serverTimezone=GMT%2B8&characterEncoding=utf-8&userSSL=false
    username: user
    password: P@ssW0rd
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
